### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by ChinaZeng** [an-Underpriviliged-ZJUer/Kaleidoscope#1]
大佬，你代码里面的目录可以写得优雅点嘛，都是windows的固定目录。用os.path弄一下嘛

**Comment by an-Underpriviliged-ZJUer** [comment]
描述清楚一下你的需求，我没明白

就是说你是想实现怎样的一个路径功能，场景是什么

我自己定的需求是能够在多台windows上不并行同一个源网站的运行（比如这里爬抖音那边爬B站，但不建议同时爬抖音或者同时爬B站

MyUtils和各项爬虫持续更新中

**Comment by ChinaZeng** [comment]
主要因为你这个目录是针对 Windows 平台弄的，Mac/Linux 用不了了。
