### ISSUE TITLE
接下来该怎么操作

### ISSUE THREAD

**Issue by a5301010** [an-Underpriviliged-ZJUer/Kaleidoscope#10]
- 下载selenium。不会请csdn。简单说明下webdriver流程：
1、到edge、chrome官方网站下载webdriver
2、将里面的.exe文件直接copy到你的系统环境变量里的python目录下

  其它一切项目中用到的模块自己学会通过pip下载 ~
- 确保项目根目录是D:/Kaleidoscope
- 更改项目根目录下的 ActiveDisk.txt。内容改成一个大写字母你要存储的磁盘。就一行，不要有多的空格换行啥的
- 新建项目根目录下的 user.txt。内容为 [C:/Users/](C:/Users/) 下的你的用户名称。
- IDE pycharm(free)（建议）
- 
以上都做好了 接下来该怎么操作，
打开下面的py文件就显示    检测到当前操作盘未初始化。请输入盘符（后期沿用，慎重！）：
怎么打开控制台 像exe程序一样

**Comment by an-Underpriviliged-ZJUer** [comment]
使用手册已经更新了
