### ISSUE TITLE
"Chrome 似乎已经在使用了"

### ISSUE THREAD

**Issue by GodeCAt** [an-Underpriviliged-ZJUer/Kaleidoscope#13]
![image](https://user-images.githubusercontent.com/98507651/222880259-a27b5ff8-25ec-40d7-acf6-1b89733b53f6.png)
![image](https://user-images.githubusercontent.com/98507651/222880269-cbe3784e-78e2-4cf4-bd29-95a4d8337f4d.png)
老师，在运行第三个文件的时候出现这种问题是为什么

**Comment by an-Underpriviliged-ZJUer** [comment]
使用本地缓存的浏览器（Chrome）同一时间只能存在一个。程序会在这个txt中添加内容每次启动带mine的浏览器的时候。并且在quit()中清除txt内容。但是如果程序中断或异常退出，就不会正常清除txt。下次运行chrome，就会检查txt内容不为空报错。因此，使用带chrome并异常中止重启时，每次需要手动清空txt内容。

这是我加的一个保险机制。如果不检查txt不为空直接启动chrome的话，在老版本中会发生异常。会导致你打开的chrome不能使用本地缓存 ，类似于无痕模式，并影响到你的正常chrome使用，需要重启电脑才能解决了。因此通过人为删除txt内容来确保你没有忘记退出上一个chrome实例。

确保退出上一个chrome实例，光退出页面不行，要打开任务管理器-资源管理器（注意不光是任务管理器，自行百度怎么打开资源管理器），关闭里面相关的chrome和chromedriver.exe进程。

**Comment by an-Underpriviliged-ZJUer** [comment]
我已经在最新的代码版本里取消了相关代码功能，不再进行繁琐的检查机制
