### ISSUE TITLE
运行DouyinDetect.py时未找到磁盘-2

### ISSUE THREAD

**Issue by xiu-ze** [an-Underpriviliged-ZJUer/Kaleidoscope#16]
以下是运行DouyinDetect.py时报错信息：
```
   11:53:39   operating DISK D                                        
   11:53:39   ScreenScale未配置，使用默认参数。
   11:53:39   MyUtils already loaded
   11:53:39   未找到磁盘-2。
```
运行前执行了以下操作：
- 将 Kaleidoscope 放在D盘下
- 在 Kaleidoscope 文件夹下新建 ActiveDisk.txt 并写入 D换行E （2行，一行是D，一行是E）
- 在D盘和E盘下分别创建 diskInfo.txt 文件，分别写入 {"name": ["ddd"]}  和 {"name": ["eee"]}
- 在 Kaleidoscope 文件夹下新建 user.txt  并写入 C:/Users/txz20
- 将 Kaleidoscope/抖音 目录下全部文件删除

请问我需要修改本项目里自带的文件 `disknames.txt` 或者 `disknames_backup.txt` 文件吗？

**Comment by an-Underpriviliged-ZJUer** [comment]
好的。这是因为我最近的更新。


我将会在后续更新使用手册。感谢您的使用和反馈。

**Comment by an-Underpriviliged-ZJUer** [comment]
按照上面的操作，或者直接pull最新的代码。
