### ISSUE TITLE
怎么没看到小红书的py文件

### ISSUE THREAD

**Issue by ranxi2001** [an-Underpriviliged-ZJUer/Kaleidoscope#2]
没有小红书的爬虫吗？烦请大佬指一下路

**Comment by an-Underpriviliged-ZJUer** [comment]
还没写 doge
刚好今天开始写哈哈

**Comment by an-Underpriviliged-ZJUer** [comment]
刚看了一下，小红书是有网页版的，页面逻辑和抖音基本上是一样的
可以参考
- [ADouyinDownload.py](./ADouyinDownload.py)
- ADouyinAccount.py
- ADouyinDetect.py

**Comment by ranxi2001** [comment]
小红书本质上是没有网页版的，网页版只有预览页面，评论区数据不全。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月12日 16:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [an-Underpriviliged-ZJUer/Kaleidoscope] 怎么没看到小红书的py文件 (Issue #2) |

刚看了一下，小红书是有网页版的，页面逻辑和抖音基本上是一样的
可以参考

ADouyinDownload.py
ADouyinAccount.py
ADouyinDetect.py

**Comment by an-Underpriviliged-ZJUer** [comment]
在大多数网站，我暂时不考虑评论区

如果仅从我开发出来的东西来讲的话，可以考虑手机虚拟器+pyautogui

这个项目不会进行底层的包解析和进行优化后的超大批量爬取（比如评论区或者其它元数据），主要是为非文本数据设计的

另外，我不清楚你需求是怎么样，你了解到的小红书网页版是有多少。对于我来说网页版和手机版是没有区别的。

**Comment by an-Underpriviliged-ZJUer** [comment]
我刚刚看了一下，好像是有评论区的？

https://www.xiaohongshu.com/discovery/item/636f2f2f000000001c034474

**Comment by ranxi2001** [comment]
评论区不是完整的，要做安卓抓包。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月12日 21:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [an-Underpriviliged-ZJUer/Kaleidoscope] 怎么没看到小红书的py文件 (Issue #2) |

我刚刚看了一下，好像是有评论区的？

https://www.xiaohongshu.com/discovery/item/636f2f2f000000001c034474
