### ISSUE TITLE
list index out of range 请问怎么修改?

### ISSUE THREAD

**Issue by tulio2833466386** [an-Underpriviliged-ZJUer/Kaleidoscope#21]
File "F:\pythonProject\translate\Kaleidoscope-main\MyUtils\__init__.py", line 3962, in <module>
    user = txt(projectpath('user.txt')).l[0]
IndexError: list index out of range

**Comment by an-Underpriviliged-ZJUer** [comment]
报错分析：
index[0], 0是列表第一位，依然out of (max) range (of the list)，说明列表连一位都没有，说明是空的
说明user.txt是空的内容
办法：检查projectpath(user.txt)的路径文件是否存在

**Comment by an-Underpriviliged-ZJUer** [comment]
可能用到了user.txt，详见请转问题统一集中楼。
