### ISSUE TITLE
老师有个问题

### ISSUE THREAD

**Issue by gaoqiang-3416** [an-Underpriviliged-ZJUer/Kaleidoscope#6]
twitterDownloader.py中的content.csv_f['y],这个csv_f是什么属性

**Comment by an-Underpriviliged-ZJUer** [comment]
奇怪了，我怎么现在才看见这个issue...
这是一个很久没有更新的文件了。
后续看情况再修复以前的twitter bug

这里应该是这样的。content是获取到的DOM树里的节点。是一个DOM 元素。获取它的高度属性，-53是因为twitter那个顶边栏有一定的高度，即使下滑也会附着在那里，所以要上移再截图，上移程度等于它的高度53.至于这个属性本来应该是这个元素的高度的一个属性，应该是字典，y值是高度。这个具体的属性名在debug过程中可见。具体是不是叫csv_f存疑。
