### ISSUE TITLE
希望能兼容linux/macos

### ISSUE THREAD

**Issue by FredYuuu** [an-Underpriviliged-ZJUer/Kaleidoscope#7]
目前MyUtils里win32con win32api没法在macos环境下运行

**Comment by an-Underpriviliged-ZJUer** [comment]
我是菜鸡没怎么用过linux
也没钱去买性价比低的macos
所以大概率不会贡献这两个os平台的东西了

不过你说的确实是一个问题。限制在win32con win32api包里确实意味着局限在windows了。不过好在MyUtils.click，MyUtils.hotkey等已经做了一层封装，这意味着如果需要改动只需要修改MyUtils的这两个函数就可以了。
不过话又说回来了项目手册里需求计划的就是在windows平台开发。

**Comment by FredYuuu** [comment]
> 我是菜鸡没怎么用过linux 也没钱去买性价比低的macos 所以大概率不会贡献这两个os平台的东西了
> 
> 不过你说的确实是一个问题。限制在win32con win32api包里确实意味着局限在windows了。不过好在MyUtils.click，MyUtils.hotkey等已经做了一层封装，这意味着如果需要改动只需要修改MyUtils的这两个函数就可以了。 不过话又说回来了项目手册里需求计划的就是在windows平台开发。

好的 还是感谢
