### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by a5301010** [an-Underpriviliged-ZJUer/Kaleidoscope#9]
operating DISK D                                                                                          
   21:22:30   disknames(Rtxt) - Rtxt set                                                                                
检测到当前操作盘未初始化。请输入盘符（后期沿用，慎重！）：
                                （已启用的唯一名）[]
麻烦给新手再详细一点的教程

**Comment by an-Underpriviliged-ZJUer** [comment]
阅读使用手册.md
